**VIDEO 1**

In [3]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('ciudadesLatam.csv')
df

Ciudad       País  Población  Visitantes
0   Ciudad de México     México    9265833    21000000
1       Buenos Aires  Argentina    3059574    15000000
2     Río de Janeiro     Brasil    6748314    13000000
3               Lima       Perú    9756020     9000000
4             Bogotá   Colombia    7181663     8000000
5  Santiago de Chile      Chile    6199241     7500000
6          São Paulo     Brasil   12333146    20000000
7          La Habana       Cuba    2164182     4000000
8             Cancún     México     888124     5000000
9          Cartagena   Colombia    1036671     3000000

In [8]:
df['Población'].mean()

np.float64(5863276.8)

In [9]:
np.round(df['Población'].mean())

np.float64(5863277.0)

In [10]:
np.min(df['Población'])

np.int64(888124)

In [11]:
np.max(df['Población'])

np.int64(12333146)

In [3]:
import pandas as pd 
import numpy as np

datos = {
    "Ciudad": ["Ciudad de México", "Buenos Aires", "Río de Janeiro", "Lima", "Bogotá", "Santiago de Chile", "São Paulo", "La Habana", "Cancún", "Cartagena"],
    "País": ["México", "Argentina", "Brasil", "Perú", "Colombia", "Chile", "Brasil", "Cuba", "México", "Colombia"],
    "Población": [9265833, 3059574, 6748314, 9756020, 7181663, 6199241, 12333146, 2164182, 888124, 1036671],
    "Visitantes": [21000000, 15000000, 13000000, 9000000, 8000000, 7500000, 20000000, 4000000, 5000000, 3000000]
}

df = pd.DataFrame(datos)

promedio_poblacion = np.round(df['Población'].mean())
promedio_poblacion

np.float64(5863277.0)

In [4]:
import pandas as pd 
import numpy as np 


datos = {
    "Ciudad": ["Ciudad de México", "Buenos Aires", "Río de Janeiro", "Lima", "Bogotá", "Santiago de Chile", "São Paulo", "La Habana", "Cancún", "Cartagena"],
    "País": ["México", "Argentina", "Brasil", "Perú", "Colombia", "Chile", "Brasil", "Cuba", "México", "Colombia"],
    "Población": [9265833, 3059574, 6748314, 9756020, 7181663, 6199241, 12333146, 2164182, 888124, 1036671],
    "Visitantes": [21000000, 15000000, 13000000, 9000000, 8000000, 7500000, 20000000, 4000000, 5000000, 3000000]
}

df = pd.DataFrame(datos)

min_visitantes = np.min(df['Población'])
min_visitantes

np.int64(888124)

In [5]:
import pandas as pd 
import numpy as np 

datos = {
    "Ciudad": ["Ciudad de México", "Buenos Aires", "Río de Janeiro", "Lima", "Bogotá", "Santiago de Chile", "São Paulo", "La Habana", "Cancún", "Cartagena"],
    "País": ["México", "Argentina", "Brasil", "Perú", "Colombia", "Chile", "Brasil", "Cuba", "México", "Colombia"],
    "Población": [9265833, 3059574, 6748314, 9756020, 7181663, 6199241, 12333146, 2164182, 888124, 1036671],
    "Visitantes": [21000000, 15000000, 13000000, 9000000, 8000000, 7500000, 20000000, 4000000, 5000000, 3000000]
}

max_visitantes = np.max(df['Visitantes'])
max_visitantes 

np.int64(21000000)

**VIDEO 2**

In [12]:
import numpy as np
import time

In [7]:
miArray = np.array([1,2,3,4,5])
miArray

array([1, 2, 3, 4, 5])

In [8]:
type(miArray)

numpy.ndarray

In [9]:
listaGrande = list(range(1000000))
arrayGrande = np.array(listaGrande)

In [10]:
type(listaGrande)

list

In [11]:
type(arrayGrande)

numpy.ndarray

In [13]:
inicioLista = time.time()
for i in listaGrande:
    i ** 2
finLista = time.time()
print("Tiempo lista: ", finLista - inicioLista)

Tiempo lista:  0.12004613876342773


In [14]:
inicioArray = time.time()
arrayGrande ** 2
finArray = time.time()

print("Tiempo lista: ", finArray - inicioArray)

Tiempo lista:  0.011113405227661133


**VIDEO 3**

In [15]:
import numpy as np
array = np.array([1,2,3])
len(array)

3

In [16]:
array.shape

(3,)

In [17]:
array2d = np.array([[1,2,3], [4,5,6]])
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
len(array2d)

2

In [19]:
array2d.shape

(2, 3)

**VIDEO 4**

In [1]:
import numpy as np

In [3]:
x = [1,2,3]
y = [1,2,3]
z = [1,2,3]


In [4]:
np.concatenate([x,y,z])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [6]:
a = [[1,2],
     [3,4]]
b = [[5,6],
     [7,8]]

np.concatenate([a,b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [7]:
np.concatenate([a,b], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
array_concatenado = np.concatenate([a,b], axis=0)
array_concatenado

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
array_concatenado.shape

(4, 2)

In [10]:
array_reformado = array_concatenado.reshape(2,4)
array_reformado

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
array_sumado = array_reformado + array_reformado
array_sumado

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [12]:
array_multi = array_reformado * array_reformado
array_multi

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [14]:
raices = np.sqrt(array_multi)
raices

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [16]:

import numpy as np 

array1 = [1,2,3,4,5]
array2 = [6,7,8,9,10]

array_concatenado = np.concatenate([array1, array2])
print(array_concatenado)

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
import numpy as np

array_original = np.array([1, 2, 3, 4, 5, 6])  # Convertir la lista a array
array_reshaped = array_original.reshape(2, 3)  # Ahora sí puedes hacer reshape

print(array_reshaped)

[[1 2 3]
 [4 5 6]]


In [20]:

import numpy as np 

a = np.array([[1,2], [3,4]])

b = np.array([[5,6], [7,8]])

suma_AB = a+b 

productoAB = a*b

In [21]:
suma_AB

array([[ 6,  8],
       [10, 12]])

In [22]:
productoAB

array([[ 5, 12],
       [21, 32]])

**VIDEO 5**

In [26]:
import numpy as np

array1d = np.array([1,2,3,4,5])

array2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [27]:
array1d

array([1, 2, 3, 4, 5])

In [28]:
array1d[0]

np.int64(1)

In [29]:
array1d[-1]

np.int64(5)

In [30]:
array2d[0]

array([1, 2, 3])

In [31]:
array2d[1][2]

np.int64(6)

In [32]:
array2d[1,2]

np.int64(6)

In [34]:
array1d[1:4]

array([2, 3, 4])

In [35]:
array2d[1,:]

array([4, 5, 6])

In [36]:
array2d[1, 1:3]

array([5, 6])

In [37]:
array2d[:,1]

array([2, 5, 8])

In [38]:
array2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [39]:
array1d > 3

array([False, False, False,  True,  True])

In [40]:
array2d % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

**VIDEO 6**

In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5,6,7,8,9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array.shape

(9,)

In [4]:
array_mod = array.reshape(3,3)
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array_mod2 = array.reshape(-1,3)
array_mod2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
array_volteado = array_mod2.transpose()
array_volteado

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
array_chato = array_mod.flatten()
array_chato

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array_ravel = array_mod.ravel()
array_ravel

array([1, 2, 3, 4, 5, 6, 7, 8, 9])